Create an OMG.lol ddns update docker image based on docker-cloudflare-ddns

diff --git a/root/etc/cont-finish.d/50-remove-record b/root/etc/cont-finish.d/50-remove-record
--- a/root/etc/cont-finish.d/50-remove-record
+++ b/root/etc/cont-finish.d/50-remove-record
@@ -1,20 +1,20 @@
 #!/usr/bin/with-contenv sh
 
-[ -f /config/cloudflare.conf ] || exit 0
+[ -f /config/omglol.conf ] || exit 0
 
-. /app/cloudflare.sh
-. /config/cloudflare.conf
+. /app/omglol.sh
+. /config/omglol.conf
 
 if [ "$DELETE_ON_STOP" == "true" ]; then
-  echo "Deleting CloudFlare DNS record $CF_RECORD_NAME..."
+  echo "Deleting OMG.lol DNS record $DDNS_RECORD_NAME..."
 
-  update=$(deleteDnsRecord $CF_ZONE_ID $CF_RECORD_ID)
+  update=$(deleteDnsRecord $DDNS_RECORD_ID)
 
-  if [ "$update" == "null" ]; then
-    echo "ERROR: Failed to delete CloudFlare DNS record $CF_RECORD_NAME"
+  if [ "$update" != 200 ]; then
+    echo "ERROR: Failed to delete OMG.lol DNS record $DDNS_RECORD_NAME"
   else
-    echo "CloudFlare DNS record $CF_RECORD_NAME deleted successfully."
+    echo "OMG.lol DNS record $DDNS_RECORD_NAME deleted successfully."
   fi
 else
-  echo "Not going to delete zone record. Deleting the zone record on container stop is disable by default."
+  echo "Not going to delete the dns record. Deleting the dns record on container stop is disable by default."
 fi
